### ISSUE TITLE
RuntimeError: There is no current event loop in thread 'MainThread'.

### ISSUE THREAD

**Issue by naurasd** [DominikBuchner/BOLDigger2#11]
Hi,

great job with the new tool!

After the top hits were successfully downloaded, I am getting the following error regarding missing event loop:

```
19:02:51: Downloaded top 100 species level records for ASV24
19:02:51: Downloaded top 100 species level records for ASV1
19:02:52: Downloaded top 100 species level records for ASV2
Downloading top 100 hits: 100%|███████████████████████████████████████████████████████████| 6/6 [00:07<00:00,  1.22s/it]
19:02:52: Species level top 100 records successfully downloaded.
19:02:52: Starting to gather download links from the all records database.
Generating download links: 7it [01:41, 14.48s/it]
19:04:33: All records download links successfully generated.
Traceback (most recent call last):
  File "/home/naurasd/.local/bin/boldigger2", line 8, in <module>
    sys.exit(main())
  File "/home/naurasd/.local/lib/python3.9/site-packages/boldigger2/__main__.py", line 44, in main
    id_engine_coi.main(arguments.fasta_file)
  File "/home/naurasd/.local/lib/python3.9/site-packages/boldigger2/id_engine_coi.py", line 584, in main
    sem = asyncio.Semaphore(6)
  File "/sw/EasyBuild/rackham/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/asyncio/locks.py", line 375, in __init__
    self._loop = events.get_event_loop()
  File "/sw/EasyBuild/rackham/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/asyncio/events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainThread'.
```
Not sure if this is a Boldigger2 problem or some issue regarding running it on our cluster infrastructure.

Best
Nauras

**Comment by naurasd** [comment]
Might be an issue because I am loading 
```
Tkinter/3.9.6-GCCcore-11.2.0
```
which is for python3.9 and Boldigger2 requires python3.10.

**Comment by DominikBuchner** [comment]
Yes you need python 3.10 or higher otherwise asyncio will not work properly
:/

naurasd ***@***.***> schrieb am Sa., 15. Juni 2024, 19:13:

**Comment by naurasd** [comment]
yes, indeed. thanks for the quick reply.
