### ISSUE TITLE
ValueError: numpy.dtype size changed

### ISSUE THREAD

**Issue by vanessamata** [DominikBuchner/BOLDigger2#12]
There's a high chance this is a silly problem, but, after some fight to install python >=3.10 (I am running Ubuntu 20.04 on WSL), I managed to install boldigger2, however, whenever I try to run it, I get the following:
```

21:05:35: Default thresholds changed!
21:05:35: Species: 99, Genus: 97, Family: 95, Order: 90, Class: 50
21:05:35: Trying to log in.
21:05:36: Login successful.
21:05:36: Starting to gather download links from species level database.
Generating download links:   0%|                                                                                | 0/1983 [00:07<?, ?it/s]
Traceback (most recent call last):
  File "/home/vmata/.local/bin/boldigger2", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/vmata/.local/lib/python3.11/site-packages/boldigger2/__main__.py", line 87, in main
    id_engine_coi.main(
  File "/home/vmata/.local/lib/python3.11/site-packages/boldigger2/id_engine_coi.py", line 477, in main
    fasta_dict = gather_download_links(
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vmata/.local/lib/python3.11/site-packages/boldigger2/id_engine_coi.py", line 156, in gather_download_links
    with pd.HDFStore(
         ^^^^^^^^^^^^
  File "/home/vmata/.local/lib/python3.11/site-packages/pandas/io/pytables.py", line 566, in __init__
    tables = import_optional_dependency("tables")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vmata/.local/lib/python3.11/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/vmata/.local/lib/python3.11/site-packages/tables/__init__.py", line 44, in <module>
    from .utilsextension import get_hdf5_version as _get_hdf5_version
  File "tables/utilsextension.pyx", line 1, in init tables.utilsextension
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

Any help will be appreciated :) especially because now I can't seem to run boldigger_cline nor boldigger gui as well :(

**Comment by DominikBuchner** [comment]
Hi Vanessa,
I've seen this for the 2nd time today.  Numpy got updated to 2.0.0 which is causing some issues until all packages that rely on it are compiled with numpy 2.0. Long story short, this error confused me all day, but I think I got it fixed.

To fix this, first uninstall numpy and boldigger2:
`pip uninstall numpy`
`pip uninstall boldigger2` 

Then reinstall boldigger2: without the cached numpy version:
`pip install  boldigger2 --no-cache-dir`

I've edited the dependencies of boldigger2 so that this error will no longer occur with new installations. Once all dependencies are solved I'll also upgrade boldigger2 to run with numpy2.

Tell me if this works for you and sorry for the inconvenience.

**Comment by vanessamata** [comment]
Thank you so much Dominik! That worked like a charm :grin:

Happy to say that it is now up and running! (and at increasing speeds!) :muscle:



```
21:47:28: Default thresholds changed!
21:47:28: Species: 99, Genus: 97, Family: 95, Order: 90, Class: 50
21:47:28: Trying to log in.
21:47:30: Login successful.
21:47:30: Starting to gather download links from species level database.
21:47:40: Query size updated to 6.
21:48:21: Query size updated to 11.
21:49:23: Query size updated to 16.
21:50:26: Query size updated to 21.
21:51:35: Query size updated to 26.
21:52:41: Query size updated to 31.
Generating download links:   4%|██▊                                                                  | 81/1983 [05:11<1:44:54,  3.31s/it]
```
