### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by lukazuvic** [DominikBuchner/BOLDigger2#16]
Dear Dominik, 
as you suggested, I have installed boldigger2 :), but I get the same error on different machines :( : 
C:\Users\lukaz>boldigger2 identify C:\Users\lukaz\Desktop\BFT
15:07:28: Trying to log in.
BOLD username: zuvic
BOLD password:
15:07:39: Login successful.
Traceback (most recent call last):
  File "C:\Users\lukaz\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\lukaz\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\lukaz\AppData\Local\Programs\Python\Python310\Scripts\boldigger2.exe\__main__.py", line 7, in 
  File "C:\Users\lukaz\AppData\Local\Programs\Python\Python310\lib\site-packages\boldigger2\__main__.py", line 87, in main
    id_engine_coi.main(
  File "C:\Users\lukaz\AppData\Local\Programs\Python\Python310\lib\site-packages\boldigger2\id_engine_coi.py", line 457, in main
    fasta_dict, fasta_name, project_directory = read_fasta(fasta_path)
  File "C:\Users\lukaz\AppData\Local\Programs\Python\Python310\lib\site-packages\boldigger2\id_engine_coi.py", line 27, in read_fasta
    fasta_dict = SeqIO.to_dict(SeqIO.parse(fasta_path, "fasta"))
  File "C:\Users\lukaz\AppData\Local\Programs\Python\Python310\lib\site-packages\Bio\SeqIO\__init__.py", line 625, in parse
    return iterator_generator(handle)
  File "C:\Users\lukaz\AppData\Local\Programs\Python\Python310\lib\site-packages\Bio\SeqIO\FastaIO.py", line 187, in __init__
    super().__init__(source, mode="t", fmt="Fasta")
  File "C:\Users\lukaz\AppData\Local\Programs\Python\Python310\lib\site-packages\Bio\SeqIO\Interfaces.py", line 64, in __init__
    self.stream = open(source, "r" + mode)
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\lukaz\\Desktop\\BFT'. 

Can you please help me solve this problem.
Thank you,
Luka

**Comment by DominikBuchner** [comment]
Hi Luka,
BFT is not your fasta file right? You need to point BOLDigger2 to the fasta file you want to identify.
Can you show the command you used?
best
Dominik

**Comment by lukazuvic** [comment]
Hi Dominik, 
sorry to bother you, as soon as I read your comment I realized where I made a mistake. Everything works perfectly, thanks again for your time.
Best,
Luka

**Comment by DominikBuchner** [comment]
All good, let me know if you encounter any troubles.
