### ISSUE TITLE
lxml_html_clean module missing

### ISSUE THREAD

**Issue by dgslos** [DominikBuchner/BOLDigger2#7]
Hi,

Can you please add lxml_html_clean to the setup.py to fix the ImportError?
```
Traceback (most recent call last):
  File "/usr/local/bin/boldigger2", line 5, in <module>
    from boldigger2.__main__ import main
  File "/usr/local/venvs/boldigger2/lib/python3.10/site-packages/boldigger2/__main__.py", line 2, in <module>
    from boldigger2 import id_engine_coi
  File "/usr/local/venvs/boldigger2/lib/python3.10/site-packages/boldigger2/id_engine_coi.py", line 1, in <module>
    import datetime, sys, more_itertools, datetime, requests_html, asyncio
  File "/usr/local/venvs/boldigger2/lib/python3.10/site-packages/requests_html.py", line 14, in <module>
    from lxml.html.clean import Cleaner
  File "/usr/local/venvs/boldigger2/lib/python3.10/site-packages/lxml/html/clean.py", line 18, in <module>
    raise ImportError(
ImportError: lxml.html.clean module is now a separate project lxml_html_clean.
Install lxml[html_clean] or lxml_html_clean directly.
```

**Comment by DominikBuchner** [comment]
fixed with 1.0.8
